---
title: Puck-It
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
show_downloads: false
favicon: /Puck-It/favicon.ico
theme: jekyll-theme-minimal
